name: Checkout infra repo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VERSION: ga-0.0.5

# defaults:
#   run:
#     working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: lehai2909/argocd-infra
          token: "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"
          ref: "main"

      # - uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f manifests/deployment.yaml

      - name: Verify
        run: |
          sed -i 's/^ *image:.*/        image: asia-southeast1-docker.pkg.dev\/web-app-hosting-lehai\/web-frontend-repo\/frontend-react-app:ga-0.0.6/' manifests/deployment.yaml
          cat manifests/deployment.yaml

    #   - name: Set up Node.js
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: "22"

    #   - name: Install Dependencies
    #     run: npm install

    #   - name: Build Application
    #     run: npm run build

    #   - name: Check
    #     run: |
    #       pwd
    #       ls -l

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to Environment
  #       run: echo "Deploying application..."
