name: Build Push Docker images to ARTIFACT REGISTRY
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "web-app-hosting-lehai" # TODO: update to your Google Cloud project ID
  VERSION: ga-0.0.2

defaults:
  run:
    working-directory: ./src

permissions:
  id-token: write
  contents: "read"

jobs:
  Build_and_Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v4

      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "web-app-hosting-lehai"
          workload_identity_provider: "projects/1078723186103/locations/global/workloadIdentityPools/github/providers/my-repo"

      - id: "gcloud"
        name: "gcloud"
        run: gcloud secrets versions access 1 --secret="github-action-secrets"

      - name: "Docker Auth"
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.auth_token }}"
          registry: "asia-southeast1-docker.pkg.dev"

      - name: "Build and push Docker container"
        run: |-
          DOCKER_TAG="asia-southeast1-docker.pkg.dev/web-app-hosting-lehai/web-frontend-repo/frontend-react-app:${VERSION}"

          docker build \
            --tag "${DOCKER_TAG}" \
            .
            
          docker push "${DOCKER_TAG}"
